_target_: data.DatasetLoader
name: Yelp2018
loss: BPR
id_only: True
k: 20
num_total_users: 31668
num_total_items: 38048
resolution: 200
embed_dim: 64
lr: 1e-3
wd: 1e-8
bs: 1561406
patience: 50
gamma: 1