dhe_k: 1024
hash_type: full
epoch: 1000

defaults:
 - _self_
 - dataset: Gowalla
 - model: MF


# Grid search for hyperparameters
hydra:
  sweeper:
    params:
      # +dataset.lr: 1e-2,5e-3,1e-3
      # +dataset.wd: 1e-4,1e-6,1e-8
      +seed: 0,1,2,3

